# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Shopify-Intern-Challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopify-Intern-Challenge
    pod 'Alamofire', '~> 5.0.0.beta.1'

  target 'Shopify-Intern-ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Shopify-Intern-ChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
